### ISSUE TITLE
Errors were discovered in the RTL version

### ISSUE THREAD

**Issue by EL2HERIF** [prosenjeet123/antonio#1]
![01](https://user-images.githubusercontent.com/80642642/111079199-a08d2c00-8501-11eb-8982-303babeeb016.png)
![02](https://user-images.githubusercontent.com/80642642/111079200-a125c280-8501-11eb-8489-78f34b5925f4.png)
![03](https://user-images.githubusercontent.com/80642642/111079201-a1be5900-8501-11eb-9024-ed5b5b97f5b5.png)
![Screenshot 2021-03-14 200232](https://user-images.githubusercontent.com/80642642/111079202-a256ef80-8501-11eb-9c6a-d04142384604.jpeg)
![Screenshot 2021-03-14 200759](https://user-images.githubusercontent.com/80642642/111079204-a3881c80-8501-11eb-89d6-70a125b013c7.jpeg)
![Screenshot 2021-03-14 200905](https://user-images.githubusercontent.com/80642642/111079205-a420b300-8501-11eb-94bb-9cc5698b823d.jpeg)
![WhatsApp Image 2021-03-14 at 7 40 43 PM](https://user-images.githubusercontent.com/80642642/111079206-a4b94980-8501-11eb-8c81-7319bcad5c67.jpeg)

**Comment by EL2HERIF** [comment]
rtl does not support mobile

![WhatsApp Image 2021-03-14 at 8 15 49 PM](https://user-images.githubusercontent.com/80642642/111079302-1d200a80-8502-11eb-8d34-e1456f6e09f6.jpeg)

**Comment by prosenjeet123** [comment]
Thanks for submitting issues, make sure you add links along with the screenshots next time for better understanding of the issues.

Committed and all the issues has been fixed  #https://github.com/prosenjeet123/antoniodev/commit/e661e7e8069dc5c5629e75fbdc56e1daf7762a99

Please download the latest from the opencart marketplace.
