### ISSUE TITLE
Errors after Update 2.2.1

### ISSUE THREAD

**Issue by EL2HERIF** [prosenjeet123/antonio#2]
****Link index.php?route=catalog/product

Original** 
![Screenshot 2021-03-14 212535](https://user-images.githubusercontent.com/80642642/111081419-ecdd6980-850b-11eb-9f33-2b0f78cf2812.jpeg)

**Antonio**
![Screenshot 2021-03-14 212613](https://user-images.githubusercontent.com/80642642/111081428-f8309500-850b-11eb-9ed3-7e9ea0b99538.jpeg)

Link index.php?route=catalog/product/edit

Original
![Screenshot 2021-03-14 212824](https://user-images.githubusercontent.com/80642642/111081485-3af26d00-850c-11eb-8425-a8e04a3ff8e6.jpeg)

Antonio
![Screenshot 2021-03-14 212758](https://user-images.githubusercontent.com/80642642/111081489-3ded5d80-850c-11eb-8f1e-ec6d78af899e.jpeg)

Link admin/index.php?route=setting/setting

Original
![Screenshot 2021-03-14 213047](https://user-images.githubusercontent.com/80642642/111081563-97ee2300-850c-11eb-9d34-64c6a369bd17.jpeg)

Antonio
![Screenshot 2021-03-14 213019](https://user-images.githubusercontent.com/80642642/111081566-9cb2d700-850c-11eb-9e2d-ef940e5814db.jpeg)**

**Comment by EL2HERIF** [comment]
Mobile View 
Link: admin/index.php?route=setting/setting

Orginal 
![WhatsApp Image 2021-03-14 at 9 46 27 PM](https://user-images.githubusercontent.com/80642642/111082107-32e7fc80-850f-11eb-9a9a-b669058eba80.jpeg)


Antonio
![WhatsApp Image 2021-03-14 at 9 46 27 PM (1)](https://user-images.githubusercontent.com/80642642/111082111-37141a00-850f-11eb-8158-1528a84bfe49.jpeg)

**Comment by EL2HERIF** [comment]
developer options button does not appear

![Screenshot 2021-03-14 224212](https://user-images.githubusercontent.com/80642642/111083663-4eef9c00-8517-11eb-86ea-0e9e53714e46.jpeg)

Antonio does not interact with other extensions
![WhatsApp Image 2021-03-14 at 10 44 37 PM](https://user-images.githubusercontent.com/80642642/111083712-8bbb9300-8517-11eb-9e0d-d2d9c35442e1.jpeg)
![WhatsApp Image 2021-03-14 at 10 45 30 PM](https://user-images.githubusercontent.com/80642642/111083713-8cecc000-8517-11eb-94c2-b7dda05b7bd3.jpeg)

**Comment by prosenjeet123** [comment]
Hi changes has been committed to #https://github.com/prosenjeet123/antoniodev/commit/bfe413ddbc7e6ec474cb3cd59ae660b6c0997381 

And about the third party modules compatibility you need to ask module developers to make it compatible with antonio.
Thanks

**Comment by EL2HERIF** [comment]
> Hi changes has been committed to #[prosenjeet123/antoniodev@bfe413d](https://github.com/prosenjeet123/antoniodev/commit/bfe413ddbc7e6ec474cb3cd59ae660b6c0997381)
> 
> And about the third party modules compatibility you need to ask module developers to make it compatible with antonio.
> Thanks

How can I download the new update?
