### ISSUE TITLE
 icon replacement/video/image options in antonio admin.

### ISSUE THREAD

**Issue by flovas** [prosenjeet123/antonio#3]
Can I remove the standard icon inserted by the opencart, to the image of a product, and be able to add another image (or video) in its place, with "Antonio"?
I need to add, my  picture(with logo , and to replace default  picture in default opencart theme...to all products, showing in categories,etc...., in that way...then after click on 1 selected product,, 
![products with default open cart picture](https://user-images.githubusercontent.com/80846165/111512301-4639d880-8758-11eb-84b4-bcf479cfcd74.png)
to remain only description text,etc...(whithout any picture...

I attach a pictures, to better explain, what i need....
![products without picture, only description](https://user-images.githubusercontent.com/80846165/111512400-61a4e380-8758-11eb-96e0-c55cee187655.png)

Thank you
![open cart default product picture](https://user-images.githubusercontent.com/80846165/111508994-f3aaed00-8754-11eb-90fa-2db6246ce6db.png)

**Comment by prosenjeet123** [comment]
not a part of admin theme, closing the issue
