### ISSUE TITLE
Antonio ..can help us to modyfy blue color, from opencart default, to another color(green, purple,etc)

### ISSUE THREAD

**Issue by flovas** [prosenjeet123/antonio#4]
Antonio ..can help us to modify blue color, from opencart default, to another color(green, purple,etc)..in store front, for categories underground, buttons,etc...???
If posible, also for cart , black background color???, and another ????

Please see pictures,

Kind Regards

![blue](https://user-images.githubusercontent.com/80846165/111513336-5ef6be00-8759-11eb-9f74-c9057e3ea6c4.png)
![cart](https://user-images.githubusercontent.com/80846165/111513424-76ce4200-8759-11eb-8e38-8a2e478da51b.png)

**Comment by prosenjeet123** [comment]
not a part of admin theme, closing the issue. thanks for raising concern.
